// MongoDB Playground for SoundWaveDB (Fase 6)
// Use this playground to test NoSQL operations, queries, and aggregations.

// 1. Select the database
use("SoundWaveDB");

// 2. Count documents in collections to verify state
console.log("=== COLLECTION COUNTS ===");
console.log("Usuarios: " + db.usuarios.countDocuments({}));
console.log("Artistas: " + db.artistas.countDocuments({}));
console.log("Canciones: " + db.canciones.countDocuments({}));
console.log("Playlists: " + db.playlists.countDocuments({}));
console.log("Reproducciones: " + db.reproducciones.countDocuments({}));
console.log("Suscripciones: " + db.suscripciones.countDocuments({}));

// 3. Query: Find active Premium users
console.log("\n=== ACTIVE PREMIUM USERS ===");
db.usuarios.find(
  { "suscripcion_activa.estado": "Activa", "suscripcion_activa.tipo_plan": "Premium" },
  { nombre_usuario: 1, email_usuario: 1, "suscripcion_activa.fecha_fin": 1 }
).pretty();

// 4. Aggregation: Top 10 most played songs with artist info
console.log("\n=== TOP 10 SONGS BY REPRODUCTIONS ===");
db.canciones.aggregate([
  { $match: { estado: "Activo" } },
  { $sort: { num_reproducciones: -1 } },
  { $limit: 10 },
  {
    $project: {
      _id: 0,
      id_cancion: 1,
      titulo_cancion: 1,
      artista: "$artista.nombre_artistico",
      reproducciones: "$num_reproducciones"
    }
  }
]);

// 5. Aggregation: Total royalties generated by each artist (0.004 USD per stream)
console.log("\n=== ROYALTIES PER ARTIST ===");
db.reproducciones.aggregate([
  {
    $group: {
      _id: "$artista.id_artista",
      nombre_artistico: { $first: "$artista.nombre_artistico" },
      total_reproducciones: { $sum: 1 }
    }
  },
  {
    $project: {
      _id: 0,
      id_artista: "$_id",
      nombre_artistico: 1,
      total_reproducciones: 1,
      regalias_estimadas_usd: { $multiply: ["$total_reproducciones", 0.004] }
    }
  },
  { $sort: { total_reproducciones: -1 } }
]);

// 6. Aggregation: Get recent plays for a specific user (e.g. user 12)
console.log("\n=== RECENT PLAYS USER 12 ===");
db.reproducciones.find(
  { "usuario.id_usuario": 12 }
).sort({ fecha_hora: -1 }).limit(5);
