const soundwaveTranslations = {
  es: {
    nav_inicio: "Inicio",
    nav_catalogo: "Catálogo",
    nav_historial: "Historial",
    nav_suscripcion: "Suscripción",
    nav_reportes: "Reportes",
    nav_soporte: "Soporte",
    nav_planes: "Planes",
    nav_administracion: "Administración",
    sidebar_user_plan_label: "Plan: ",
    sidebar_btn_cerrar_sesion: "Cerrar Sesión",
    dropdown_ajustes: "Ajustes",
    dropdown_idioma: "Idioma",
    dropdown_ayuda: "Obtener ayuda",
    dropdown_planes: "Planes",
    dropdown_suscripcion: "Suscripción",
    dropdown_info: "Más información",
    dropdown_cerrar_sesion: "Cerrar sesión",
    public_nav_soporte: "Soporte",
    public_nav_planes: "Planes",
    public_nav_iniciar_sesion: "Iniciar sesión",
    public_nav_registrarse: "Registrarse",
    footer_copyright: "SoundWave. Todos los derechos reservados.",
    lang_modal_title: "Seleccionar Idioma",
    lang_modal_close: "Cerrar",
    admin_modal_title: "Verificación de Acceso",
    admin_modal_placeholder: "Contraseña de Administrador",
    admin_modal_confirm: "Confirmar",
    admin_modal_cancel: "Cancelar",
    admin_sidebar_mode: "Modo Administrador",
    admin_sidebar_oyentes: "Oyentes",
    admin_sidebar_artistas: "Artistas",
    admin_sidebar_sistema: "Sistema",
    admin_sidebar_reportes: "Reportes",
    admin_sidebar_user_profile: "Admin Activo",
    admin_header_title: "Consola de Control del Sistema",
    admin_title: "Panel de Administración",
    admin_subtitle: "Consola de Control",
    admin_oyentes_title: "Oyentes Registrados",
    admin_oyentes_subtitle: "Gestión de Usuarios",
    admin_oyentes_search_label: "Buscar Oyente",
    admin_oyentes_filter_status: "Estado",
    admin_oyentes_filter_all: "Todos",
    admin_oyentes_filter_active: "Activo",
    admin_oyentes_filter_inactive: "Inactivo",
    admin_oyentes_filter_plan: "Plan",
    admin_oyentes_filter_any: "Cualquiera",
    admin_oyentes_table_id: "ID",
    admin_oyentes_table_name: "Nombre",
    admin_oyentes_table_email: "Correo Electrónico",
    admin_oyentes_table_plan: "Plan",
    admin_oyentes_table_status: "Estado",
    admin_oyentes_table_actions: "Acciones",
    admin_oyentes_btn_edit: "Editar",
    admin_oyentes_btn_delete: "Eliminar",
    admin_oyentes_btn_protected: "Protegido",
    admin_oyentes_create_title: "Registrar Nuevo Oyente",
    admin_oyentes_create_sub: "Nuevo Registro",
    admin_oyentes_create_name: "Nombre Completo",
    admin_oyentes_create_email: "Correo Electrónico",
    admin_oyentes_create_country: "País",
    admin_oyentes_create_plan: "Plan Inicial",
    admin_oyentes_create_btn: "Registrar Oyente",
    admin_oyentes_edit_title: "Editar Perfil de Oyente",
    admin_oyentes_edit_sub: "Actualizar Datos",
    admin_oyentes_edit_name: "Nombre",
    admin_oyentes_edit_email: "Correo",
    admin_oyentes_edit_status: "Estado",
    admin_oyentes_edit_btn_cancel: "Cancelar",
    admin_oyentes_edit_btn_save: "Guardar",
    admin_artistas_title: "Artistas en la Plataforma",
    admin_artistas_sub: "Catálogo de Artistas",
    admin_artistas_search_label: "Buscar Artista",
    admin_artistas_table_name: "Artista",
    admin_artistas_table_country: "País",
    admin_artistas_table_plays: "Reproducciones Totales",
    admin_sistema_users: "Usuarios Totales",
    admin_sistema_songs: "Canciones en Catálogo",
    admin_sistema_albums: "Álbumes Registrados",
    admin_sistema_plays: "Escuchas Totales",
    landing_hero_title: "La ola de sonido <span class=\"accent\">definitiva</span>",
    landing_hero_subtitle: "Calidad acústica sin compromisos. Descubre un catálogo de artistas y canciones en alta fidelidad, pensado para conectar de verdad con la música que amas.",
    landing_btn_probar: "Empezar",
    landing_btn_ver_planes: "Ver Planes",
    landing_features_title: "Sonido Premium, Experiencia Exclusiva",
    landing_features_subtitle: "Diseñado para audiófilos que valoran la pureza y los detalles en cada nota musical.",
    landing_feat1_title: "Alta Fidelidad (Hi-Res)",
    landing_feat1_desc: "Transmisión de audio sin pérdidas a 24-bit para percibir cada instrumento tal como fue grabado.",
    landing_feat2_title: "Catálogo",
    landing_feat2_desc: "Explora una selección de artistas, álbumes y playlists pensada para enriquecer tus sentidos.",
    landing_feat3_title: "Sin Anuncios",
    landing_feat3_desc: "Concentración total en la música sin interrupciones ni anuncios comerciales molestos.",
    landing_feat4_title: "Algoritmo Personalizado",
    landing_feat4_desc: "Recomendaciones basadas en tus gustos reales y patrones acústicos de escucha.",
    landing_drive_title: "Empieza tu viaje musical hoy",
    landing_drive_subtitle: "Accede de inmediato al catálogo completo y experimenta la diferencia.",
    landing_drive_btn: "Registrarse Ahora",
    planes_title: "Encuentra tu plan ideal",
    planes_subtitle: "Cambia de plan en cualquier momento según tus necesidades acústicas y disfruta de SoundWave.",
    planes_tab_gratuito_title: "Plan Gratuito",
    planes_tab_gratuito_price: "$0 / siempre",
    planes_tab_gratuito_feat1: "Acceso al catálogo de canciones completo",
    planes_tab_gratuito_feat2: "Reproducción con calidad estándar (128kbps)",
    planes_tab_gratuito_feat3: "Soporte técnico mediante centro de ayuda",
    planes_tab_gratuito_feat4: "Anuncios visuales y de audio ocasionales",
    planes_tab_gratuito_btn: "Comenzar Gratis",
    planes_tab_premium_title: "Plan Premium",
    planes_tab_premium_price: "$9.99 / mes",
    planes_tab_premium_feat1: "Audio en Alta Resolución sin pérdidas (24-bit Hi-Res)",
    planes_tab_premium_feat2: "Reproducción 100% sin anuncios ni interrupciones",
    planes_tab_premium_feat3: "Guarda tus canciones favoritas para escuchar sin conexión",
    planes_tab_premium_feat4: "Soporte técnico prioritario y especializado",
    planes_tab_premium_btn: "Adquirir Premium",
    planes_active_plan_btn: "Tu plan actual",
    planes_tab_premium_upgrade_btn: "Mejorar a Premium",
    planes_tab_estudiante_title: "Plan Estudiante",
    planes_tab_estudiante_price: "$4.99 / mes",
    planes_tab_estudiante_badge: "Para estudiantes",
    planes_tab_estudiante_discount: "50% de descuento",
    planes_tab_estudiante_note: "Requiere verificación de estatus estudiantil activo",
    planes_tab_estudiante_btn: "Adquirir Estudiante",
    planes_tab_estudiante_upgrade_btn: "Mejorar a Estudiante",
    planes_tab_familiar_title: "Plan Familiar",
    planes_tab_familiar_price: "$14.99 / mes",
    planes_tab_familiar_badge: "Hasta 6 perfiles",
    planes_tab_familiar_feat1: "Hasta 6 perfiles individuales bajo una sola suscripción",
    planes_tab_familiar_feat2: "Cada perfil con su propia biblioteca, historial y recomendaciones personalizadas",
    planes_tab_familiar_btn: "Adquirir Familiar",
    planes_tab_familiar_upgrade_btn: "Mejorar a Familiar",
    planes_tab_anual_title: "Plan Anual",
    planes_tab_anual_price: "$99.99 / año",
    planes_tab_anual_badge: "Ahorra 2 meses",
    planes_tab_anual_note: "equivalente a $8.33 al mes",
    planes_tab_anual_btn: "Adquirir Anual",
    planes_tab_anual_upgrade_btn: "Mejorar a Anual",
    planes_faq_title: "Preguntas frecuentes sobre planes",
    planes_faq_q1: "¿Puedo cancelar mi plan en cualquier momento?",
    planes_faq_a1: "Sí, puedes cancelar tu suscripción Premium en cualquier momento desde tu panel de suscripción. Seguirás teniendo acceso a las ventajas hasta el final del periodo facturado.",
    planes_faq_q2: "¿Cómo se procesan los pagos?",
    planes_faq_a2: "Los pagos se procesan de forma segura a través de nuestra pasarela de pagos certificada, con cifrado de extremo a extremo. Tu suscripción se activa de inmediato tras la confirmación de la transacción.",
    planes_faq_more: "¿Tienes más dudas? Visita nuestro Centro de Ayuda",
    planes_cta_title: "Comienza hoy mismo con SoundWave",
    planes_cta_text: "Únete a millones de oyentes y disfruta de una calidad sonora insuperable adaptada a tu estilo de vida",
    planes_cta_btn_dashboard: "Ir a mi Dashboard",
    planes_cta_btn_start: "Comenzar ahora",
    soporte_title: "Centro de Ayuda",
    soporte_subtitle: "Encuentra respuestas rápidas sobre tu cuenta, planes y reproducción",
    soporte_cat1_title: "Cuenta y Seguridad",
    soporte_cat1_desc: "Modificar correo, recuperar contraseña y gestionar sesiones",
    soporte_cat2_title: "Planes y Pagos",
    soporte_cat2_desc: "Métodos de pago, facturación y cambio a Premium",
    soporte_cat3_title: "Reproducción y Calidad",
    soporte_cat3_desc: "Configuración de audio Hi-Res, codecs y solución de problemas",
    soporte_faq_title: "Preguntas Frecuentes",
    soporte_q1: "¿Cómo puedo cambiar mi plan de Gratuito a Premium?",
    soporte_a1: "Puedes cambiar tu plan en cualquier momento desde la sección de Suscripción en el menú lateral. Selecciona el plan Premium, ingresa el método de pago y tu cuenta se actualizará de inmediato.",
    soporte_q2: "¿Qué es el audio de Alta Resolución (Hi-Res)?",
    soporte_a2: "El audio Hi-Res de SoundWave ofrece sonido sin pérdidas a 24 bits, preservando todos los detalles y el rango dinámico de la grabación original de estudio. Requiere una suscripción Premium activa.",
    soporte_q3: "¿Cómo recupero mi contraseña de acceso?",
    soporte_a3: "Si no recuerdas tu contraseña, puedes ir a la pantalla de inicio de sesión y hacer click en ¿Olvidaste tu contraseña?, o contactar a soporte si posees inconvenientes adicionales.",
    soporte_search_placeholder: "Busca tu pregunta...",
    soporte_no_results: "No encontramos ninguna pregunta que coincida con tu búsqueda. Intenta con otras palabras clave.",
    soporte_contact_title: "¿No encontraste lo que buscabas?",
    soporte_contact_text: "Nuestro equipo de atención al cliente está siempre listo para ayudarte con soporte técnico y administrativo personalizado.",
    soporte_contact_btn: "Contáctanos por Correo",
    dashboard_welcome: "Bienvenido de vuelta",
    dashboard_sub: "Explora tu música y estadísticas en tiempo real",
    dashboard_stat_songs: "Canciones Escuchadas",
    dashboard_stat_albums: "Álbumes Guardados",
    dashboard_stat_hours: "Horas de Escucha",
    dashboard_title_recientes: "Historial Reciente",
    dashboard_col_song: "Canción",
    dashboard_col_artist: "Artista",
    dashboard_col_date: "Fecha y Hora",
    dashboard_title_top: "Top Canciones Globales",
    dashboard_col_reps: "Reproducciones",
    dashboard_col_duration: "Duración",
    dashboard_title_recs: "Recomendaciones para ti",
    dashboard_col_genre: "Género",
    dashboard_empty_albums: "No tienes álbumes guardados en tu biblioteca.",
    dashboard_empty_history: "No hay reproducciones registradas recientemente.",
    dashboard_empty_recs: "No se encontraron recomendaciones basadas en tu historial.",
    dashboard_stat_songs_sub: "Actividad real en plataforma",
    dashboard_stat_albums_sub: "Sincronizados en tu espacio",
    dashboard_stat_hours_sub: "Tiempo total en SoundWave",
    dashboard_profile_title: "Perfil Editorial",
    dashboard_profile_name: "Nombre del Oyente",
    dashboard_profile_subscription: "Nivel de Suscripción",
    dashboard_profile_status: "Estado de la Cuenta",
    dashboard_profile_premium_active: "Premium Activo",
    dashboard_profile_free_account: "Cuenta Gratuita",
    dashboard_library_title: "Biblioteca Personal",
    dashboard_library_sub: "Colección de Álbumes",
    dashboard_col_reg_date: "Fecha de Registro",
    dashboard_empty_library: "Tu biblioteca personal se encuentra vacía.",
    dashboard_recs_sub: "Descubrimientos para Ti",
    dashboard_recent_sub: "Últimas Reproducciones",
    dashboard_top_sub: "Las más escuchadas",
    dashboard_empty_top: "No se registran datos acumulados de reproducción.",
    catalogo_title: "Catálogo de Canciones",
    catalogo_subtitle: "Explora canciones, álbumes y playlists populares en SoundWave",
    catalogo_filter_artist: "Artista",
    catalogo_filter_all_artists: "Todos los artistas",
    catalogo_filter_genre: "Género",
    catalogo_filter_all_genres: "Todos los géneros",
    catalogo_btn_apply: "Aplicar Filtros",
    catalogo_btn_clear: "Limpiar Filtros",
    catalogo_title_songs: "Resultados de Búsqueda",
    catalogo_col_album: "Álbum",
    catalogo_btn_play: "Escuchar",
    catalogo_title_popular_artists: "Artistas Populares",
    catalogo_col_country: "País",
    catalogo_col_total_plays: "Escuchas",
    catalogo_search_label: "Buscar canción o artista",
    catalogo_search_placeholder: "Título, artista o álbum...",
    catalogo_ranking_sub: "Ranking por reproducciones",
    catalogo_col_rank: "Puesto",
    catalogo_col_country: "País de Origen",
    catalogo_col_plays: "Total Reproducciones",
    catalogo_empty_artists_search: "Ningún artista coincide con la búsqueda.",
    catalogo_empty_artists: "No se registran datos de artistas en el catálogo.",
    catalogo_top_20_plays: "Top 20 Más Escuchadas",
    catalogo_col_play: "Escuchar",
    catalogo_col_title: "Título",
    catalogo_col_duration: "Duración",
    catalogo_empty_songs_search: "Ninguna canción coincide con la búsqueda.",
    catalogo_empty_songs: "No se registran canciones con los filtros seleccionados.",
    catalogo_filtering_by: "Filtrando por:",
    catalogo_remove_filter: "Quitar filtro",
    historial_title: "Mi Historial de Reproducción",
    historial_subtitle: "Consulta y filtra todas tus escuchas en la plataforma",
    historial_filter_start: "Fecha Inicio",
    historial_filter_end: "Fecha Fin",
    historial_btn_filter: "Filtrar Historial",
    historial_btn_pdf: "Exportar PDF",
    historial_col_duration: "Tiempo Escuchado",
    historial_empty: "No se encontraron registros de reproducción para los filtros seleccionados.",
    historial_filter_genre: "Filtrar por Género",
    historial_filter_all_genres: "Todos los géneros",
    historial_audit_report: "Reporte de Auditoría",
    historial_top_10_title: "Top 10 Oyente",
    historial_recent_badge: "Recientes",
    historial_empty_top: "Sin reproducciones disponibles.",
    suscripcion_title: "Gestión de Suscripción",
    suscripcion_active_plan: "Plan Activo Actualmente",
    suscripcion_active_plan_val: "Plan Activo",
    suscripcion_start_date: "Fecha de Inicio",
    suscripcion_end_date: "Próxima Renovación",
    suscripcion_status: "Estado de Suscripción",
    suscripcion_active_val: "Activa",
    suscripcion_change_title: "¿Deseas cambiar de plan?",
    suscripcion_change_desc: "Si deseas actualizar tu suscripción o cancelar la renovación, puedes hacerlo seleccionando un nuevo plan en la sección de planes.",
    suscripcion_btn_planes: "Ver Planes Disponibles",
    suscripcion_btn_cancel: "Cancelar Cuenta",
    sub_res_title: "Resultado de la Transacción en SoundWaveDB",
    sub_res_plan: "Plan de Cuenta:",
    sub_res_date: "Nueva Fecha de Vencimiento:",
    sub_res_db_status: "Estado Actualizado en BD:",
    sub_status_title: "Estado de Suscripción Actual (Consulta de BD)",
    sub_payment_gateway_title: "Pasarela de Pagos Interna",
    sub_payment_gateway_desc: "Estás gestionando el ciclo de vida transaccional para la suscripción de la cuenta <strong>Suscripción ID: 1</strong>. La operación invocará de manera atómica las reglas de negocio en el servidor SQL Server.",
    sub_label_payment_method: "Método de Pago Corporativo",
    sub_opt_credit_card: "Tarjeta de Crédito Corporativa",
    sub_opt_paypal: "PayPal Business",
    sub_opt_bank_transfer: "Transferencia Bancaria Directa",
    sub_label_simulate_status: "Simular Estado de la Transacción",
    sub_opt_success: "Transacción Exitosa (Aprobar Renovación)",
    sub_opt_fail: "Transacción Declinada (Forzar Vencimiento)",
    sub_btn_process: "Procesar Transacción en Base de Datos",
    sub_val_indefinite: "Indefinida",
    sub_val_inactive: "Inactiva",
    reportes_title: "Reportes y Estadísticas",
    reportes_subtitle: "Informes de reproducción globales y actividad del sistema",
    reportes_tab_plays: "Reproducciones",
    reportes_tab_users: "Usuarios",
    reportes_tab_artistas: "Artistas",
    reportes_tab_planes: "Suscripciones",
    reportes_plays_title: "Reporte de Canciones Populares",
    reportes_plays_col_song: "Canción",
    reportes_plays_col_artist: "Artista",
    reportes_plays_col_duration: "Duración",
    reportes_plays_col_reps: "Escuchas",
    reportes_users_title: "Reporte de Oyentes Registrados",
    reportes_users_col_name: "Nombre",
    reportes_users_col_email: "Correo Electrónico",
    reportes_users_col_status: "Estado",
    reportes_users_col_plan: "Plan",
    reportes_artistas_title: "Reporte de Artistas",
    reportes_artistas_col_name: "Artista",
    reportes_artistas_col_country: "País",
    reportes_artistas_col_reps: "Reproducciones Totales",
    reportes_planes_title: "Distribución de Planes de Suscripción",
    reportes_planes_col_plan: "Tipo de Plan",
    reportes_planes_col_count: "Cantidad Usuarios",
    detail_artist_title: "Perfil del Artista",
    detail_artist_country: "País de Origen",
    detail_artist_plays: "Reproducciones Totales",
    detail_artist_songs: "Canciones Populares",
    detail_album_title: "Detalle del Álbum",
    detail_album_release: "Año de Lanzamiento",
    detail_album_songs: "Canciones del Álbum",
    detail_playlist_title: "Detalle de Playlist",
    detail_playlist_owner: "Creado por",
    detail_playlist_songs: "Canciones en Playlist",
    ajustes_title: "Ajustes de Perfil",
    ajustes_subtitle: "Mi Cuenta",
    ajustes_label_name: "Nombre de Usuario",
    ajustes_label_email: "Correo Electrónico",
    ajustes_label_pass: "Contraseña",
    ajustes_btn_save: "Guardar Cambios",
    info_about_title: "Acerca de SoundWave",
    info_about_sub: "Nuestra Misión",
    info_about_desc: "SoundWave es una plataforma de streaming de música premium diseñada para conectar a los oyentes con sus artistas favoritos. Fundada en la elegancia de la simplicidad y el diseño de alta calidad, nos dedicamos a ofrecer una experiencia sonora sin compromisos, donde la fidelidad del sonido y el respeto por la creatividad artística convergen.",
    info_team_title: "Equipo de Desarrollo",
    info_team_sub: "Creadores",
    info_team_role_backend: "Desarrollador Backend",
    info_team_role_frontend: "Desarrolladora Frontend",
    info_team_role_fullstack: "Desarrollador Fullstack",
    info_terms_title: "Términos y Condiciones",
    info_terms_sub: "Legal",
    info_terms_desc1: "Al acceder y utilizar SoundWave, usted acepta estar sujeto a los siguientes términos y condiciones de servicio. La plataforma proporciona acceso a contenidos de audio en streaming bajo suscripción gratuita y premium.",
    info_terms_desc2: "Todo el contenido musical, carátulas de álbumes, metadatos y código de software son propiedad intelectual exclusiva de SoundWave y sus respectivos licenciantes. El uso de la plataforma es estrictamente personal y no comercial.",
    info_terms_desc3: "Nos reservamos el derecho de modificar o retirar cualquier parte del servicio, incluyendo tarifas, planes y disponibilidad del catálogo musical en cualquier momento y sin previo aviso.",
    reportes_page_title: "Reportes Ejecutivos y de Auditoría",
    reportes_page_sub: "Base de Datos SoundWave",
    reportes_page_desc: "Ejecución directa de Stored Procedures y exportación en formato PDF con diseño institucional. Seleccione uno de los reportes a continuación para configurar sus parámetros y visualizar o descargar sus resultados.",
    rep1_title: "Top 10 Canciones Más Reproducidas",
    rep1_desc: "Muestra las 10 canciones con mayor número de reproducciones en la plataforma, detallando el artista, álbum y total de reproducciones.",
    rep2_title: "Artistas Más Populares",
    rep2_desc: "Ranking de artistas de la plataforma ordenados por el total de reproducciones acumuladas de todas sus canciones publicadas.",
    rep3_title: "Suscripciones Activas",
    rep3_desc: "Muestra todos los usuarios con suscripciones en estado activa o premium, incluyendo las fechas de inicio, fin y montos pagados.",
    rep4_title: "Ingresos y Regalías por Artista",
    rep4_select_artist: "Seleccionar Artista",
    rep4_select_option: "-- Seleccione un Artista --",
    rep5_title: "Historial de Reproducción por Usuario",
    rep5_select_user: "Seleccionar Oyente",
    rep5_select_option: "-- Seleccione un Usuario --",
    rep5_date_from: "Desde (Opcional)",
    rep5_date_to: "Hasta (Opcional)",
    rep6_title: "Álbumes Guardados por Usuario",
    rep6_select_user: "Seleccionar Oyente",
    rep6_select_option: "-- Seleccione un Usuario --",
    rep_btn_view: "Ver Reporte",
    rep_btn_pdf: "Descargar PDF",
    rep_results_title: "Resultados de Consulta",
    rep_results_error: "Error al ejecutar stored procedure:",
    rep_results_empty: "No se encontraron registros para los parámetros seleccionados.",
    detail_artist_label: "Artista",
    detail_artist_debut: "Debut:",
    detail_artist_contact: "Contacto:",
    detail_artist_total_plays: "Total Reproducciones:",
    detail_artist_albums: "Álbumes y Sencillos",
    detail_artist_listen: "Escuchar",
    detail_artist_title_col: "Título",
    detail_artist_duration: "Duración",
    detail_artist_reps: "Reproducciones",
    detail_artist_empty_album: "Este álbum no contiene canciones registradas.",
    detail_artist_no_albums: "No se registran álbumes para este artista.",
    detail_artist_back: "Volver al catálogo",
    detail_album_label: "Álbum",
    detail_album_artist: "Artista:",
    detail_album_release: "Lanzamiento:",
    detail_album_total: "Total Canciones:",
    detail_album_list_title: "Lista de Canciones",
    detail_album_listen: "Escuchar",
    detail_album_title_col: "Título",
    detail_album_genres: "Géneros",
    detail_album_duration: "Duración",
    detail_album_reps: "Reproducciones",
    detail_album_no_genre: "Sin género",
    detail_album_empty: "Este álbum no contiene canciones registradas.",
    detail_album_back: "Volver al catálogo",
    detail_album_see_artist: "Ver Artista",
    detail_playlist_public: "Pública",
    detail_playlist_private: "Privada",
    detail_playlist_creator: "Creador:",
    detail_playlist_total: "Total Canciones:",
    detail_playlist_list_title: "Canciones en la Playlist",
    detail_playlist_order: "Orden",
    detail_playlist_listen: "Escuchar",
    detail_playlist_title_col: "Título",
    detail_playlist_artist: "Artista",
    detail_playlist_album: "Álbum",
    detail_playlist_duration: "Duración",
    detail_playlist_empty: "Esta playlist se encuentra vacía.",
    detail_playlist_back: "Volver al Inicio"
  },
  en: {
    nav_inicio: "Home",
    nav_catalogo: "Catalog",
    nav_historial: "History",
    nav_suscripcion: "Subscription",
    nav_reportes: "Reports",
    nav_soporte: "Support",
    nav_planes: "Plans",
    nav_administracion: "Administration",
    sidebar_user_plan_label: "Plan: ",
    sidebar_btn_cerrar_sesion: "Log Out",
    dropdown_ajustes: "Settings",
    dropdown_idioma: "Language",
    dropdown_ayuda: "Get help",
    dropdown_planes: "Plans",
    dropdown_suscripcion: "Subscription",
    dropdown_info: "More info",
    dropdown_cerrar_sesion: "Log out",
    public_nav_soporte: "Support",
    public_nav_planes: "Plans",
    public_nav_iniciar_sesion: "Log In",
    public_nav_registrarse: "Sign Up",
    footer_copyright: "SoundWave. All rights reserved.",
    lang_modal_title: "Select Language",
    lang_modal_close: "Close",
    admin_modal_title: "Access Verification",
    admin_modal_placeholder: "Admin Password",
    admin_modal_confirm: "Confirm",
    admin_modal_cancel: "Cancel",
    admin_sidebar_mode: "Administrator Mode",
    admin_sidebar_oyentes: "Listeners",
    admin_sidebar_artistas: "Artists",
    admin_sidebar_sistema: "System",
    admin_sidebar_reportes: "Reports",
    admin_sidebar_user_profile: "Active Admin",
    admin_header_title: "System Control Console",
    admin_title: "Administration Panel",
    admin_subtitle: "Control Console",
    admin_oyentes_title: "Registered Listeners",
    admin_oyentes_subtitle: "User Management",
    admin_oyentes_search_label: "Search Listener",
    admin_oyentes_filter_status: "Status",
    admin_oyentes_filter_all: "All",
    admin_oyentes_filter_active: "Active",
    admin_oyentes_filter_inactive: "Inactive",
    admin_oyentes_filter_plan: "Plan",
    admin_oyentes_filter_any: "Any",
    admin_oyentes_table_id: "ID",
    admin_oyentes_table_name: "Name",
    admin_oyentes_table_email: "Email Address",
    admin_oyentes_table_plan: "Plan",
    admin_oyentes_table_status: "Status",
    admin_oyentes_table_actions: "Actions",
    admin_oyentes_btn_edit: "Edit",
    admin_oyentes_btn_delete: "Delete",
    admin_oyentes_btn_protected: "Protected",
    admin_oyentes_create_title: "Register New Listener",
    admin_oyentes_create_sub: "New Registration",
    admin_oyentes_create_name: "Full Name",
    admin_oyentes_create_email: "Email Address",
    admin_oyentes_create_country: "Country",
    admin_oyentes_create_plan: "Initial Plan",
    admin_oyentes_create_btn: "Register Listener",
    admin_oyentes_edit_title: "Edit Listener Profile",
    admin_oyentes_edit_sub: "Update Data",
    admin_oyentes_edit_name: "Name",
    admin_oyentes_edit_email: "Email",
    admin_oyentes_edit_status: "Status",
    admin_oyentes_edit_btn_cancel: "Cancel",
    admin_oyentes_edit_btn_save: "Save",
    admin_artistas_title: "Artists on the Platform",
    admin_artistas_sub: "Artists Catalog",
    admin_artistas_search_label: "Search Artist",
    admin_artistas_table_name: "Artist",
    admin_artistas_table_country: "Country",
    admin_artistas_table_plays: "Total Plays",
    admin_sistema_users: "Total Users",
    admin_sistema_songs: "Songs in Catalog",
    admin_sistema_albums: "Registered Albums",
    admin_sistema_plays: "Total Plays",
    landing_hero_title: "The ultimate <span class=\"accent\">wave of sound</span>",
    landing_hero_subtitle: "Uncompromising acoustic quality. Discover a catalog of artists and songs in high fidelity, designed to truly connect with the music you love.",
    landing_btn_probar: "Start",
    landing_btn_ver_planes: "See Plans",
    landing_features_title: "Premium Sound, Exclusive Experience",
    landing_features_subtitle: "Designed for audiophiles who value purity and detail in every musical note.",
    landing_feat1_title: "High Fidelity (Hi-Res)",
    landing_feat1_desc: "Lossless 24-bit audio streaming to perceive every instrument just as it was recorded.",
    landing_feat2_title: "Catalog",
    landing_feat2_desc: "Explore a selection of artists, albums, and playlists designed to enrich your senses.",
    landing_feat3_title: "Ad-Free",
    landing_feat3_desc: "Total concentration on the music without interruptions or annoying commercial ads.",
    landing_feat4_title: "Personalized Algorithm",
    landing_feat4_desc: "Recommendations based on your actual tastes and acoustic listening patterns.",
    landing_drive_title: "Start your musical journey today",
    landing_drive_subtitle: "Access the entire catalog immediately and experience the difference.",
    landing_drive_btn: "Register Now",
    planes_title: "Find your ideal plan",
    planes_subtitle: "Change plans at any time according to your acoustic needs and enjoy SoundWave.",
    planes_tab_gratuito_title: "Free Plan",
    planes_tab_gratuito_price: "$0 / always",
    planes_tab_gratuito_feat1: "Access to the complete song catalog",
    planes_tab_gratuito_feat2: "Playback with standard quality (128kbps)",
    planes_tab_gratuito_feat3: "Tech support via help center",
    planes_tab_gratuito_feat4: "Occasional visual and audio ads",
    planes_tab_gratuito_btn: "Start for Free",
    planes_tab_premium_title: "Premium Plan",
    planes_tab_premium_price: "$9.99 / month",
    planes_tab_premium_feat1: "Lossless High-Resolution Audio (24-bit Hi-Res)",
    planes_tab_premium_feat2: "Playback 100% ad-free and without interruptions",
    planes_tab_premium_feat3: "Save your favorite songs to listen offline",
    planes_tab_premium_feat4: "Priority and specialized tech support",
    planes_tab_premium_btn: "Get Premium",
    planes_active_plan_btn: "Your current plan",
    planes_tab_premium_upgrade_btn: "Upgrade to Premium",
    planes_tab_estudiante_title: "Student Plan",
    planes_tab_estudiante_price: "$4.99 / month",
    planes_tab_estudiante_badge: "For students",
    planes_tab_estudiante_discount: "50% off",
    planes_tab_estudiante_note: "Requires active student status verification",
    planes_tab_estudiante_btn: "Get Student",
    planes_tab_estudiante_upgrade_btn: "Upgrade to Student",
    planes_tab_familiar_title: "Family Plan",
    planes_tab_familiar_price: "$14.99 / month",
    planes_tab_familiar_badge: "Up to 6 profiles",
    planes_tab_familiar_feat1: "Up to 6 individual profiles under one subscription",
    planes_tab_familiar_feat2: "Each profile with its own library, history, and personalized recommendations",
    planes_tab_familiar_btn: "Get Family",
    planes_tab_familiar_upgrade_btn: "Upgrade to Family",
    planes_tab_anual_title: "Annual Plan",
    planes_tab_anual_price: "$99.99 / year",
    planes_tab_anual_badge: "Save 2 months",
    planes_tab_anual_note: "equivalent to $8.33 a month",
    planes_tab_anual_btn: "Get Annual",
    planes_tab_anual_upgrade_btn: "Upgrade to Annual",
    planes_faq_title: "Frequently asked questions about plans",
    planes_faq_q1: "Can I cancel my plan at any time?",
    planes_faq_a1: "Yes, you can cancel your Premium subscription at any time from your subscription panel. You will continue to have access to the benefits until the end of the billing period.",
    planes_faq_q2: "How are payments processed?",
    planes_faq_a2: "Payments are processed securely through our certified payment gateway, with end-to-end encryption. Your subscription is activated immediately upon confirmation of the transaction.",
    planes_faq_more: "Have more questions? Visit our Help Center",
    planes_cta_title: "Start with SoundWave today",
    planes_cta_text: "Join millions of listeners and enjoy insuperable sound quality tailored to your lifestyle",
    planes_cta_btn_dashboard: "Go to my Dashboard",
    planes_cta_btn_start: "Start now",
    soporte_title: "Help Center",
    soporte_subtitle: "Find quick answers about your account, plans, and playback",
    soporte_cat1_title: "Account & Security",
    soporte_cat1_desc: "Change email, recover password, and manage sessions",
    soporte_cat2_title: "Plans & Payments",
    soporte_cat2_desc: "Payment methods, billing, and switching to Premium",
    soporte_cat3_title: "Playback & Quality",
    soporte_cat3_desc: "Hi-Res audio settings, codecs, and troubleshooting",
    soporte_faq_title: "Frequently Asked Questions",
    soporte_q1: "How can I change my plan from Free to Premium?",
    soporte_a1: "You can change your plan at any time from the Subscription section in the sidebar menu. Select the Premium plan, enter the payment method, and your account will be updated immediately.",
    soporte_q2: "What is High-Resolution (Hi-Res) audio?",
    soporte_a2: "SoundWave's Hi-Res audio offers lossless 24-bit sound, preserving all details and the dynamic range of the original studio recording. It requires an active Premium subscription.",
    soporte_q3: "How do I recover my access password?",
    soporte_a3: "If you do not remember your password, you can go to the login screen and click \"Forgot your password?\", or contact support if you have additional issues.",
    soporte_search_placeholder: "Search your question...",
    soporte_no_results: "We didn't find any questions matching your search. Try other keywords.",
    soporte_contact_title: "Didn't find what you were looking for?",
    soporte_contact_text: "Our customer support team is always ready to help you with personalized technical and administrative support.",
    soporte_contact_btn: "Contact Us by Email",
    dashboard_welcome: "Welcome back",
    dashboard_sub: "Explore your music and statistics in real time",
    dashboard_stat_songs: "Songs Played",
    dashboard_stat_albums: "Saved Albums",
    dashboard_stat_hours: "Hours Played",
    dashboard_title_recientes: "Recent History",
    dashboard_col_song: "Song",
    dashboard_col_artist: "Artist",
    dashboard_col_date: "Date & Time",
    dashboard_title_top: "Top Global Songs",
    dashboard_col_reps: "Plays",
    dashboard_col_duration: "Duration",
    dashboard_title_recs: "Recommendations for you",
    dashboard_col_genre: "Genre",
    dashboard_empty_albums: "You don't have any saved albums in your library.",
    dashboard_empty_history: "No plays recorded recently.",
    dashboard_empty_recs: "No recommendations found based on your history.",
    dashboard_stat_songs_sub: "Real activity in platform",
    dashboard_stat_albums_sub: "Synchronized in your library",
    dashboard_stat_hours_sub: "Total time in SoundWave",
    dashboard_profile_title: "Editorial Profile",
    dashboard_profile_name: "Listener's Name",
    dashboard_profile_subscription: "Subscription Level",
    dashboard_profile_status: "Account Status",
    dashboard_profile_premium_active: "Active Premium",
    dashboard_profile_free_account: "Free Account",
    dashboard_library_title: "Personal Library",
    dashboard_library_sub: "Albums Collection",
    dashboard_col_reg_date: "Registration Date",
    dashboard_empty_library: "Your personal library is empty.",
    dashboard_recs_sub: "Discoveries for You",
    dashboard_recent_sub: "Latest Plays",
    dashboard_top_sub: "Most Played",
    dashboard_empty_top: "No accumulated playback data recorded.",
    catalogo_title: "Song Catalog",
    catalogo_subtitle: "Explore songs, albums, and popular playlists on SoundWave",
    catalogo_filter_artist: "Artist",
    catalogo_filter_all_artists: "All artists",
    catalogo_filter_genre: "Genre",
    catalogo_filter_all_genres: "All genres",
    catalogo_btn_apply: "Apply Filters",
    catalogo_btn_clear: "Clear Filters",
    catalogo_title_songs: "Search Results",
    catalogo_col_album: "Album",
    catalogo_btn_play: "Listen",
    catalogo_title_popular_artists: "Popular Artists",
    catalogo_col_country: "Country",
    catalogo_col_total_plays: "Plays",
    catalogo_search_label: "Search song or artist",
    catalogo_search_placeholder: "Title, artist, or album...",
    catalogo_ranking_sub: "Ranking by plays",
    catalogo_col_rank: "Rank",
    catalogo_col_country: "Country of Origin",
    catalogo_col_plays: "Total Plays",
    catalogo_empty_artists_search: "No artists match the search.",
    catalogo_empty_artists: "No artists recorded in the catalog.",
    catalogo_top_20_plays: "Top 20 Most Played",
    catalogo_col_play: "Play",
    catalogo_col_title: "Title",
    catalogo_col_duration: "Duration",
    catalogo_empty_songs_search: "No songs match the search.",
    catalogo_empty_songs: "No songs recorded with selected filters.",
    catalogo_filtering_by: "Filtering by:",
    catalogo_remove_filter: "Remove filter",
    historial_title: "My Playback History",
    historial_subtitle: "View and filter all your plays on the platform",
    historial_filter_start: "Start Date",
    historial_filter_end: "End Date",
    historial_btn_filter: "Filter History",
    historial_btn_pdf: "Export PDF",
    historial_col_duration: "Listening Time",
    historial_empty: "No playback records found for the selected filters.",
    historial_filter_genre: "Filter by Genre",
    historial_filter_all_genres: "All genres",
    historial_audit_report: "Audit Report",
    historial_top_10_title: "Listener's Top 10",
    historial_recent_badge: "Recent",
    historial_empty_top: "No plays available.",
    suscripcion_title: "Subscription Management",
    suscripcion_active_plan: "Currently Active Plan",
    suscripcion_active_plan_val: "Active Plan",
    suscripcion_start_date: "Start Date",
    suscripcion_end_date: "Next Renewal",
    suscripcion_status: "Subscription Status",
    suscripcion_active_val: "Active",
    suscripcion_change_title: "Want to change plans?",
    suscripcion_change_desc: "If you want to update your subscription or cancel renewal, you can do so by selecting a new plan in the plans section.",
    suscripcion_btn_planes: "See Available Plans",
    suscripcion_btn_cancel: "Cancel Account",
    sub_res_title: "Transaction Result in SoundWaveDB",
    sub_res_plan: "Account Plan:",
    sub_res_date: "New Expiration Date:",
    sub_res_db_status: "Updated Status in DB:",
    sub_status_title: "Current Subscription Status (DB Query)",
    sub_payment_gateway_title: "Internal Payment Gateway",
    sub_payment_gateway_desc: "You are managing the transactional lifecycle for account subscription <strong>Subscription ID: 1</strong>. The operation will atomically invoke business rules in the SQL Server database.",
    sub_label_payment_method: "Corporate Payment Method",
    sub_opt_credit_card: "Corporate Credit Card",
    sub_opt_paypal: "PayPal Business",
    sub_opt_bank_transfer: "Direct Bank Transfer",
    sub_label_simulate_status: "Simulate Transaction Status",
    sub_opt_success: "Successful Transaction (Approve Renewal)",
    sub_opt_fail: "Declined Transaction (Force Expiration)",
    sub_btn_process: "Process Transaction in Database",
    sub_val_indefinite: "Indefinite",
    sub_val_inactive: "Inactive",
    reportes_title: "Reports & Statistics",
    reportes_subtitle: "Global playback reports and system activity",
    reportes_tab_plays: "Plays",
    reportes_tab_users: "Users",
    reportes_tab_artistas: "Artists",
    reportes_tab_planes: "Subscriptions",
    reportes_plays_title: "Popular Songs Report",
    reportes_plays_col_song: "Song",
    reportes_plays_col_artist: "Artist",
    reportes_plays_col_duration: "Duration",
    reportes_plays_col_reps: "Plays",
    reportes_users_title: "Registered Listeners Report",
    reportes_users_col_name: "Name",
    reportes_users_col_email: "Email Address",
    reportes_users_col_status: "Status",
    reportes_users_col_plan: "Plan",
    reportes_artistas_title: "Artists Report",
    reportes_artistas_col_name: "Artist",
    reportes_artistas_col_country: "Country",
    reportes_artistas_col_reps: "Total Plays",
    reportes_planes_title: "Subscription Plans Distribution",
    reportes_planes_col_plan: "Plan Type",
    reportes_planes_col_count: "User Count",
    detail_artist_title: "Artist Profile",
    detail_artist_country: "Country of Origin",
    detail_artist_plays: "Total Plays",
    detail_artist_songs: "Popular Songs",
    detail_album_title: "Album Details",
    detail_album_release: "Release Year",
    detail_album_songs: "Album Songs",
    detail_playlist_title: "Playlist Details",
    detail_playlist_owner: "Created by",
    detail_playlist_songs: "Songs in Playlist",
    ajustes_title: "Profile Settings",
    ajustes_subtitle: "My Account",
    ajustes_label_name: "Username",
    ajustes_label_email: "Email Address",
    ajustes_label_pass: "Password",
    ajustes_btn_save: "Save Changes",
    info_about_title: "About SoundWave",
    info_about_sub: "Our Mission",
    info_about_desc: "SoundWave is a premium music streaming platform designed to connect listeners with their favorite artists. Built on the elegance of simplicity and high-quality design, we are dedicated to offering an uncompromising sound experience, where audio fidelity and respect for artistic creativity converge.",
    info_team_title: "Development Team",
    info_team_sub: "Creators",
    info_team_role_backend: "Backend Developer",
    info_team_role_frontend: "Frontend Developer",
    info_team_role_fullstack: "Fullstack Developer",
    info_terms_title: "Terms & Conditions",
    info_terms_sub: "Legal",
    info_terms_desc1: "By accessing and using SoundWave, you agree to be bound by the following terms and conditions of service. The platform provides access to streaming audio content under free and premium subscriptions.",
    info_terms_desc2: "All musical content, album art, metadata, and software code are the exclusive intellectual property of SoundWave and its respective licensors. Use of the platform is strictly personal and non-commercial.",
    info_terms_desc3: "We reserve the right to modify or withdraw any part of the service, including fees, plans, and catalog availability at any time without prior notice.",
    reportes_page_title: "Executive & Audit Reports",
    reportes_page_sub: "SoundWave Database",
    reportes_page_desc: "Direct execution of Stored Procedures and PDF export with institutional design. Select one of the reports below to configure its parameters and view or download results.",
    rep1_title: "Top 10 Most Played Songs",
    rep1_desc: "Shows the 10 songs with the highest number of plays on the platform, detailing the artist, album, and total plays.",
    rep2_title: "Most Popular Artists",
    rep2_desc: "Ranking of platform artists ordered by the total accumulated plays of all their published songs.",
    rep3_title: "Active Subscriptions",
    rep3_desc: "Shows all users with subscriptions in active or premium status, including start dates, end dates, and amounts paid.",
    rep4_title: "Revenue & Royalties by Artist",
    rep4_select_artist: "Select Artist",
    rep4_select_option: "-- Select an Artist --",
    rep5_title: "Playback History by User",
    rep5_select_user: "Select Listener",
    rep5_select_option: "-- Select a User --",
    rep5_date_from: "From (Optional)",
    rep5_date_to: "To (Optional)",
    rep6_title: "Albums Saved by User",
    rep6_select_user: "Select Listener",
    rep6_select_option: "-- Select a User --",
    rep_btn_view: "View Report",
    rep_btn_pdf: "Download PDF",
    rep_results_title: "Query Results",
    rep_results_error: "Error running stored procedure:",
    rep_results_empty: "No records found for the selected parameters.",
    detail_artist_label: "Artist",
    detail_artist_debut: "Debut:",
    detail_artist_contact: "Contact:",
    detail_artist_total_plays: "Total Plays:",
    detail_artist_albums: "Albums & Singles",
    detail_artist_listen: "Play",
    detail_artist_title_col: "Title",
    detail_artist_duration: "Duration",
    detail_artist_reps: "Plays",
    detail_artist_empty_album: "This album contains no registered songs.",
    detail_artist_no_albums: "No albums registered for this artist.",
    detail_artist_back: "Back to catalog",
    detail_album_label: "Album",
    detail_album_artist: "Artist:",
    detail_album_release: "Release:",
    detail_album_total: "Total Songs:",
    detail_album_list_title: "Song List",
    detail_album_listen: "Play",
    detail_album_title_col: "Title",
    detail_album_genres: "Genres",
    detail_album_duration: "Duration",
    detail_album_reps: "Plays",
    detail_album_no_genre: "No genre",
    detail_album_empty: "This album contains no registered songs.",
    detail_album_back: "Back to catalog",
    detail_album_see_artist: "View Artist",
    detail_playlist_public: "Public",
    detail_playlist_private: "Private",
    detail_playlist_creator: "Creator:",
    detail_playlist_total: "Total Songs:",
    detail_playlist_list_title: "Songs in Playlist",
    detail_playlist_order: "Order",
    detail_playlist_listen: "Play",
    detail_playlist_title_col: "Title",
    detail_playlist_artist: "Artist",
    detail_playlist_album: "Album",
    detail_playlist_duration: "Duration",
    detail_playlist_empty: "This playlist is empty.",
    detail_playlist_back: "Back to Home"
  },
  fr: {
    nav_inicio: "Accueil",
    nav_catalogo: "Catalogue",
    nav_historial: "Historique",
    nav_suscripcion: "Abonnement",
    nav_reportes: "Rapports",
    nav_soporte: "Support",
    nav_planes: "Formules",
    nav_administracion: "Administration",
    sidebar_user_plan_label: "Plan : ",
    sidebar_btn_cerrar_sesion: "Se Déconnecter",
    dropdown_ajustes: "Paramètres",
    dropdown_idioma: "Langue",
    dropdown_ayuda: "Obtenir de l'aide",
    dropdown_planes: "Formules",
    dropdown_suscripcion: "Abonnement",
    dropdown_info: "Plus d'infos",
    dropdown_cerrar_sesion: "Se déconnecter",
    public_nav_soporte: "Support",
    public_nav_planes: "Formules",
    public_nav_iniciar_sesion: "Connexion",
    public_nav_registrarse: "S'inscrire",
    footer_copyright: "SoundWave. Tous droits réservés.",
    lang_modal_title: "Choisir la langue",
    lang_modal_close: "Fermer",
    admin_modal_title: "Vérification d'accès",
    admin_modal_placeholder: "Mot de passe administrateur",
    admin_modal_confirm: "Confirmer",
    admin_modal_cancel: "Annuler",
    admin_sidebar_mode: "Mode Administrateur",
    admin_sidebar_oyentes: "Auditeurs",
    admin_sidebar_artistas: "Artistes",
    admin_sidebar_sistema: "Système",
    admin_sidebar_reportes: "Rapports",
    admin_sidebar_user_profile: "Admin Actif",
    admin_header_title: "Console de contrôle du système",
    admin_title: "Panneau d'administration",
    admin_subtitle: "Console de contrôle",
    admin_oyentes_title: "Auditeurs enregistrés",
    admin_oyentes_subtitle: "Gestion des utilisateurs",
    admin_oyentes_search_label: "Rechercher un auditeur",
    admin_oyentes_filter_status: "État",
    admin_oyentes_filter_all: "Tous",
    admin_oyentes_filter_active: "Actif",
    admin_oyentes_filter_inactive: "Inactif",
    admin_oyentes_filter_plan: "Plan",
    admin_oyentes_filter_any: "N'importe lequel",
    admin_oyentes_table_id: "ID",
    admin_oyentes_table_name: "Nom",
    admin_oyentes_table_email: "Adresse e-mail",
    admin_oyentes_table_plan: "Plan",
    admin_oyentes_table_status: "État",
    admin_oyentes_table_actions: "Actions",
    admin_oyentes_btn_edit: "Modifier",
    admin_oyentes_btn_delete: "Supprimer",
    admin_oyentes_btn_protected: "Protégé",
    admin_oyentes_create_title: "Enregistrer un nouvel auditeur",
    admin_oyentes_create_sub: "Nouvelle inscription",
    admin_oyentes_create_name: "Nom complet",
    admin_oyentes_create_email: "Adresse e-mail",
    admin_oyentes_create_country: "Pays",
    admin_oyentes_create_plan: "Formule initiale",
    admin_oyentes_create_btn: "Enregistrer l'auditeur",
    admin_oyentes_edit_title: "Modifier le profil de l'auditeur",
    admin_oyentes_edit_sub: "Mettre à jour",
    admin_oyentes_edit_name: "Nom",
    admin_oyentes_edit_email: "E-mail",
    admin_oyentes_edit_status: "État",
    admin_oyentes_edit_btn_cancel: "Annuler",
    admin_oyentes_edit_btn_save: "Enregistrer",
    admin_artistas_title: "Artistes sur la plateforme",
    admin_artistas_sub: "Catalogue des artistes",
    admin_artistas_search_label: "Rechercher un artiste",
    admin_artistas_table_name: "Artiste",
    admin_artistas_table_country: "Pays",
    admin_artistas_table_plays: "Total des écoutes",
    admin_sistema_users: "Nombre total d'utilisateurs",
    admin_sistema_songs: "Chansons au catalogue",
    admin_sistema_albums: "Albums enregistrés",
    admin_sistema_plays: "Total des écoutes",
    landing_hero_title: "La vague de son <span class=\"accent\">ultime</span>",
    landing_hero_subtitle: "Qualité acoustique sans compromis. Découvrez un catalogue d'artistes et de chansons en haute fidélité, conçu pour vous connecter véritablement à la musique que vous aimez.",
    landing_btn_probar: "Commencer",
    landing_btn_ver_planes: "Voir les formules",
    landing_features_title: "Son Premium, Expérience Exclusive",
    landing_features_subtitle: "Conçu pour les audiophiles qui apprécient la pureté et les détails de chaque note de musique.",
    landing_feat1_title: "Haute Fidélité (Hi-Res)",
    landing_feat1_desc: "Streaming audio 24 bits sans perte pour percevoir chaque instrument tel qu'il a été enregistré.",
    landing_feat2_title: "Catalogue",
    landing_feat2_desc: "Explorez une sélection d'artistes, d'albums et de playlists conçue pour enrichir vos sens.",
    landing_feat3_title: "Sans Publicité",
    landing_feat3_desc: "Concentration totale sur la musique sans interruptions ni publicités commerciales ennuyeuses.",
    landing_feat4_title: "Algorithme Personnalisé",
    landing_feat4_desc: "Recommandations basées sur vos goûts réels et vos habitudes d'écoute acoustique.",
    landing_drive_title: "Commencez votre voyage musical aujourd'hui",
    landing_drive_subtitle: "Accédez immédiatement à l'ensemble du catalogue et découvrez la différence.",
    landing_drive_btn: "S'inscrire maintenant",
    planes_title: "Trouvez votre formule idéale",
    planes_subtitle: "Changez de formule à tout moment en fonction de vos besoins acoustiques et profitez de SoundWave.",
    planes_tab_gratuito_title: "Formule Gratuite",
    planes_tab_gratuito_price: "0 € / toujours",
    planes_tab_gratuito_feat1: "Accès au catalogue complet de chansons",
    planes_tab_gratuito_feat2: "Lecture en qualité standard (128kbps)",
    planes_tab_gratuito_feat3: "Support technique via le centre d'aide",
    planes_tab_gratuito_feat4: "Publicités visuelles et audio occasionnelles",
    planes_tab_gratuito_btn: "Commencer gratuitement",
    planes_tab_premium_title: "Formule Premium",
    planes_tab_premium_price: "9,99 € / mois",
    planes_tab_premium_feat1: "Audio haute résolution sans perte (24 bits Hi-Res)",
    planes_tab_premium_feat2: "Lecture 100% sans publicité ni interruption",
    planes_tab_premium_feat3: "Enregistrez vos chansons préférées pour les écouter hors connexion",
    planes_tab_premium_feat4: "Support technique prioritaire et spécialisé",
    planes_tab_premium_btn: "Obtenir Premium",
    planes_active_plan_btn: "Votre formule actuelle",
    planes_tab_premium_upgrade_btn: "Passer à Premium",
    planes_tab_estudiante_title: "Formule Étudiante",
    planes_tab_estudiante_price: "4,99 € / mois",
    planes_tab_estudiante_badge: "Pour étudiants",
    planes_tab_estudiante_discount: "-50% de réduction",
    planes_tab_estudiante_note: "Nécessite la vérification du statut d'étudiant actif",
    planes_tab_estudiante_btn: "Obtenir Étudiante",
    planes_tab_estudiante_upgrade_btn: "Passer à Étudiante",
    planes_tab_familiar_title: "Formule Familiale",
    planes_tab_familiar_price: "14,99 € / mois",
    planes_tab_familiar_badge: "Jusqu'à 6 profils",
    planes_tab_familiar_feat1: "Jusqu'à 6 profils individuels sous un seul abonnement",
    planes_tab_familiar_feat2: "Chaque profil avec sa propre bibliothèque, son historique et ses recommandations personnalisées",
    planes_tab_familiar_btn: "Obtenir Familiale",
    planes_tab_familiar_upgrade_btn: "Passer à Familiale",
    planes_tab_anual_title: "Formule Annuelle",
    planes_tab_anual_price: "99,99 € / an",
    planes_tab_anual_badge: "Économisez 2 mois",
    planes_tab_anual_note: "équivalant a 8,33 € par mois",
    planes_tab_anual_btn: "Obtenir Annuelle",
    planes_tab_anual_upgrade_btn: "Passer à Annuelle",
    planes_faq_title: "Questions fréquemment posées sur les formules",
    planes_faq_q1: "Puis-je annuler ma formule à tout moment ?",
    planes_faq_a1: "Oui, vous pouvez annuler votre abonnement Premium à tout moment depuis votre panneau d'abonnement. Vous continuerez à avoir accès aux avantages jusqu'à la fin de la période de facturation.",
    planes_faq_q2: "Comment les paiements sont-ils traités ?",
    planes_faq_a2: "Les paiements sont traités en toute sécurité via notre passerelle de paiement certifiée, avec un cryptage de bout en bout. Votre abonnement est activé immédiatement après confirmation de la transaction.",
    planes_faq_more: "Vous avez d'autres questions ? Visitez notre centre d'aide",
    planes_cta_title: "Commencez avec SoundWave dès aujourd'hui",
    planes_cta_text: "Rejoignez des millions d'auditeurs et profitez d'une qualité sonore inégalée et adaptée à votre style de vie",
    planes_cta_btn_dashboard: "Aller sur mon tableau de bord",
    planes_cta_btn_start: "Commencer maintenant",
    soporte_title: "Centre d'aide",
    soporte_subtitle: "Trouvez des réponses rapides concernant votre compte, vos formules et la lecture",
    soporte_cat1_title: "Compte et sécurité",
    soporte_cat1_desc: "Modifier l'e-mail, récupérer le mot de passe et gérer les sessions",
    soporte_cat2_title: "Formules et paiements",
    soporte_cat2_desc: "Moyens de paiement, facturation et passage à Premium",
    soporte_cat3_title: "Lecture et qualité",
    soporte_cat3_desc: "Paramètres audio Hi-Res, codecs et dépannage",
    soporte_faq_title: "Questions Fréquentes",
    soporte_q1: "Comment puis-je passer de la formule Gratuite à la formule Premium ?",
    soporte_a1: "Vous pouvez modifier votre formule à tout moment depuis la section Abonnement du menu latéral. Sélectionnez la formule Premium, saisissez le mode de paiement et votre compte sera mis à jour immédiatement.",
    soporte_q2: "Qu'est-ce que l'audio Haute Résolution (Hi-Res) ?",
    soporte_a2: "L'audio Hi-Res de SoundWave offre un son 24 bits sans perte, préservant tous les détails et la plage dynamique de l'enregistrement studio d'origine. Nécessite un abonnement Premium actif.",
    soporte_q3: "Comment récupérer mon mot de passe d'accès ?",
    soporte_a3: "Si vous ne vous souvenez de votre mot de passe, vous pouvez vous rendre sur l'écran de connexion et cliquer sur « Mot de passe oublié ? », ou contacter le support si vous rencontrez d'autres problèmes.",
    soporte_search_placeholder: "Recherchez votre question...",
    soporte_no_results: "Nous n'avons trouvé aucune question correspondant à votre recherche. Essayez d'autres mots-clés.",
    soporte_contact_title: "Vous n'avez pas trouvé ce que vous cherchiez ?",
    soporte_contact_text: "Notre équipe de support client est toujours prête à vous aider avec un support technique et administratif personnalisé.",
    soporte_contact_btn: "Contactez-nous par e-mail",
    dashboard_welcome: "Bon retour",
    dashboard_sub: "Explorez votre musique et vos statistiques en temps réel",
    dashboard_stat_songs: "Chansons écoutées",
    dashboard_stat_albums: "Albums sauvegardés",
    dashboard_stat_hours: "Heures d'écoute",
    dashboard_title_recientes: "Historique Récent",
    dashboard_col_song: "Chanson",
    dashboard_col_artist: "Artiste",
    dashboard_col_date: "Date et heure",
    dashboard_title_top: "Top Chansons Globales",
    dashboard_col_reps: "Écoutes",
    dashboard_col_duration: "Durée",
    dashboard_title_recs: "Recommandations pour vous",
    dashboard_col_genre: "Genre",
    dashboard_empty_albums: "Vous n'avez aucun album sauvegardé dans votre bibliothèque.",
    dashboard_empty_history: "Aucune écoute enregistrée récemment.",
    dashboard_empty_recs: "Aucune recommandation trouvée basée sur votre historique.",
    dashboard_stat_songs_sub: "Activité réelle sur la plateforme",
    dashboard_stat_albums_sub: "Synchronisés dans votre espace",
    dashboard_stat_hours_sub: "Temps total sur SoundWave",
    dashboard_profile_title: "Profil éditorial",
    dashboard_profile_name: "Nom de l'auditeur",
    dashboard_profile_subscription: "Niveau d'abonnement",
    dashboard_profile_status: "Statut du compte",
    dashboard_profile_premium_active: "Premium Actif",
    dashboard_profile_free_account: "Compte Gratuit",
    dashboard_library_title: "Bibliothèque personnelle",
    dashboard_library_sub: "Collection d'albums",
    dashboard_col_reg_date: "Date d'enregistrement",
    dashboard_empty_library: "Votre bibliothèque personnelle est vide.",
    dashboard_recs_sub: "Découvertes pour vous",
    dashboard_recent_sub: "Dernières écoutes",
    dashboard_top_sub: "Les plus écoutées",
    dashboard_empty_top: "Aucune donnée de lecture cumulée enregistrée.",
    catalogo_title: "Catalogue de chansons",
    catalogo_subtitle: "Explorez les chansons, les albums et les playlists populaires sur SoundWave",
    catalogo_filter_artist: "Artiste",
    catalogo_filter_all_artists: "Tous les artistes",
    catalogo_filter_genre: "Genre",
    catalogo_filter_all_genres: "Tous les genres",
    catalogo_btn_apply: "Appliquer les filtres",
    catalogo_btn_clear: "Effacer les filtres",
    catalogo_title_songs: "Résultats de recherche",
    catalogo_col_album: "Album",
    catalogo_btn_play: "Écouter",
    catalogo_title_popular_artists: "Artistes Populaires",
    catalogo_col_country: "Pays",
    catalogo_col_total_plays: "Écoutes",
    catalogo_search_label: "Rechercher une chanson ou un artiste",
    catalogo_search_placeholder: "Titre, artiste ou album...",
    catalogo_ranking_sub: "Classement par écoutes",
    catalogo_col_rank: "Rang",
    catalogo_col_country: "Pays d'origine",
    catalogo_col_plays: "Total des écoutes",
    catalogo_empty_artists_search: "Aucun artiste ne correspond à la recherche.",
    catalogo_empty_artists: "Aucun artiste enregistré dans le catalogue.",
    catalogo_top_20_plays: "Top 20 des plus écoutées",
    catalogo_col_play: "Écouter",
    catalogo_col_title: "Titre",
    catalogo_col_duration: "Durée",
    catalogo_empty_songs_search: "Aucune chanson ne correspond à la recherche.",
    catalogo_empty_songs: "Aucune chanson enregistrée avec les filtres sélectionnés.",
    catalogo_filtering_by: "Filtré par :",
    catalogo_remove_filter: "Supprimer le filtre",
    historial_title: "Mon historique de lecture",
    historial_subtitle: "Consultez et filtrez toutes vos écoutes sur la plateforme",
    historial_filter_start: "Date de début",
    historial_filter_end: "Date de fin",
    historial_btn_filter: "Filtrer l'historique",
    historial_btn_pdf: "Exporter en PDF",
    historial_col_duration: "Temps d'écoute",
    historial_empty: "Aucun enregistrement de lecture trouvé pour les filtres sélectionnés.",
    historial_filter_genre: "Filtrer par genre",
    historial_filter_all_genres: "Tous les genres",
    historial_audit_report: "Rapport d'audit",
    historial_top_10_title: "Top 10 de l'auditeur",
    historial_recent_badge: "Récents",
    historial_empty_top: "Aucune écoute disponible.",
    suscripcion_title: "Gestion de l'abonnement",
    suscripcion_active_plan: "Formule actuellement active",
    suscripcion_active_plan_val: "Formule active",
    suscripcion_start_date: "Date de début",
    suscripcion_end_date: "Prochain renouvellement",
    suscripcion_status: "État de l'abonnement",
    suscripcion_active_val: "Active",
    suscripcion_change_title: "Vous souhaitez changer de formule ?",
    suscripcion_change_desc: "Si vous souhaitez mettre à jour votre abonnement ou annuler le renouvellement, vous pouvez le faire en sélectionnant une nouvelle formule dans la section des formules.",
    suscripcion_btn_planes: "Voir les formules disponibles",
    suscripcion_btn_cancel: "Annuler le compte",
    sub_res_title: "Résultat de la transaction dans SoundWaveDB",
    sub_res_plan: "Plan de compte :",
    sub_res_date: "Nouvelle date d'expiration :",
    sub_res_db_status: "Statut mis à jour dans la BD :",
    sub_status_title: "Statut actuel de l'abonnement (Requête BD)",
    sub_payment_gateway_title: "Passerelle de paiement interne",
    sub_payment_gateway_desc: "Vous gérez le cycle de vie transactionnel de l'abonnement du compte <strong>ID Abonnement : 1</strong>. L'opération invoquera de manière atomique les règles métier sur le serveur SQL Server.",
    sub_label_payment_method: "Moyen de paiement d'entreprise",
    sub_opt_credit_card: "Carte de crédit d'entreprise",
    sub_opt_paypal: "PayPal Business",
    sub_opt_bank_transfer: "Virement bancaire direct",
    sub_label_simulate_status: "Simuler le statut de la transaction",
    sub_opt_success: "Transaction réussie (approuver le renouvellement)",
    sub_opt_fail: "Transaction déclinée (forcer l'expiration)",
    sub_btn_process: "Traiter la transaction dans la base de données",
    sub_val_indefinite: "Indéfinie",
    sub_val_inactive: "Inactive",
    reportes_title: "Rapports et statistiques",
    reportes_subtitle: "Rapports d'écoute globaux et activité du système",
    reportes_tab_plays: "Reproducciones",
    reportes_tab_users: "Utilisateurs",
    reportes_tab_artistas: "Artistes",
    reportes_tab_planes: "Abonnements",
    reportes_plays_title: "Rapport des chansons populaires",
    reportes_plays_col_song: "Chanson",
    reportes_plays_col_artist: "Artiste",
    reportes_plays_col_duration: "Durée",
    reportes_plays_col_reps: "Écoutes",
    reportes_users_title: "Rapport des auditeurs enregistrés",
    reportes_users_col_name: "Nom",
    reportes_users_col_email: "Adresse e-mail",
    reportes_users_col_status: "État",
    reportes_users_col_plan: "Plan",
    reportes_artistas_title: "Rapport des artistes",
    reportes_artistas_col_name: "Artiste",
    reportes_artistas_col_country: "Pays",
    reportes_artistas_col_reps: "Total des écoutes",
    reportes_planes_title: "Répartition des formules d'abonnement",
    reportes_planes_col_plan: "Type de formule",
    reportes_planes_col_count: "Nombre d'utilisateurs",
    detail_artist_title: "Profil de l'artiste",
    detail_artist_country: "Pays d'origine",
    detail_artist_plays: "Total des écoutes",
    detail_artist_songs: "Chansons Populaires",
    detail_album_title: "Détails de l'album",
    detail_album_release: "Année de sortie",
    detail_album_songs: "Chansons de l'album",
    detail_playlist_title: "Détails de la playlist",
    detail_playlist_owner: "Créé par",
    detail_playlist_songs: "Chansons de la playlist",
    ajustes_title: "Paramètres du profil",
    ajustes_subtitle: "Mon compte",
    ajustes_label_name: "Nom d'utilisateur",
    ajustes_label_email: "Adresse e-mail",
    ajustes_label_pass: "Mot de passe",
    ajustes_btn_save: "Enregistrer les modifications",
    info_about_title: "À propos de SoundWave",
    info_about_sub: "Notre mission",
    info_about_desc: "SoundWave est une plateforme de streaming musical haut de gamme conçue pour connecter les auditeurs avec leurs artistes préférés. Fondée sur l'élégance de la simplicité et un design de haute qualité, nous nous engageons à offrir une expérience sonore sans compromis, où fidélité audio et respect de la créativité artistique convergent.",
    info_team_title: "Équipe de développement",
    info_team_sub: "Créateurs",
    info_team_role_backend: "Développeur Backend",
    info_team_role_frontend: "Développeuse Frontend",
    info_team_role_fullstack: "Développeur Fullstack",
    info_terms_title: "Conditions Générales",
    info_terms_sub: "Mentions légales",
    info_terms_desc1: "En accédant et en utilisant SoundWave, vous acceptez d'être lié par les conditions générales d'utilisation suivantes. La plateforme fournit un accès à du contenu audio en streaming sous abonnements gratuits et premium.",
    info_terms_desc2: "Tout le contenu musical, les pochettes d'albums, les métadonnées et le code du logiciel sont la propriété intellectuelle exclusive de SoundWave et de ses concédants de licence respectifs. L'utilisation de la plateforme est strictement personnelle et non commerciale.",
    info_terms_desc3: "Nous nous réservons le droit de modifier ou de retirer tout ou partie du service, y compris les tarifs, formules et la disponibilité du catalogue à tout moment et sans préavis.",
    reportes_page_title: "Rapports Exécutifs et d'Audit",
    reportes_page_sub: "Base de Données SoundWave",
    reportes_page_desc: "Exécution directe de procédures stockées et exportation PDF avec design institutionnel. Sélectionnez un rapport pour configurer ses paramètres et visualiser ou télécharger les résultats.",
    rep1_title: "Top 10 Chansons les Plus Écoutées",
    rep1_desc: "Affiche les 10 chansons avec le plus grand nombre d'écoutes sur la plateforme, avec l'artiste, l'album et le total d'écoutes.",
    rep2_title: "Artistes les Plus Populaires",
    rep2_desc: "Classement des artistes de la plateforme selon le total d'écoutes accumulées de toutes leurs chansons publiées.",
    rep3_title: "Abonnements Actifs",
    rep3_desc: "Affiche tous les utilisateurs avec des abonnements actifs ou premium, incluant les dates de début, de fin et les montants payés.",
    rep4_title: "Revenus et Redevances par Artiste",
    rep4_select_artist: "Sélectionner un artiste",
    rep4_select_option: "-- Sélectionnez un artiste --",
    rep5_title: "Historique de lecture par utilisateur",
    rep5_select_user: "Sélectionner un auditeur",
    rep5_select_option: "-- Sélectionnez un utilisateur --",
    rep5_date_from: "Du (Optionnel)",
    rep5_date_to: "Au (Optionnel)",
    rep6_title: "Albums sauvegardés par utilisateur",
    rep6_select_user: "Sélectionner un auditeur",
    rep6_select_option: "-- Sélectionnez un utilisateur --",
    rep_btn_view: "Voir le rapport",
    rep_btn_pdf: "Télécharger PDF",
    rep_results_title: "Résultats de la requête",
    rep_results_error: "Erreur lors de l'exécution de la procédure stockée :",
    rep_results_empty: "Aucun enregistrement trouvé pour les paramètres sélectionnés.",
    detail_artist_label: "Artiste",
    detail_artist_debut: "Début :",
    detail_artist_contact: "Contact :",
    detail_artist_total_plays: "Total des écoutes :",
    detail_artist_albums: "Albums et Singles",
    detail_artist_listen: "Écouter",
    detail_artist_title_col: "Titre",
    detail_artist_duration: "Durée",
    detail_artist_reps: "Écoutes",
    detail_artist_empty_album: "Cet album ne contient aucune chanson enregistrée.",
    detail_artist_no_albums: "Aucun album enregistré pour cet artiste.",
    detail_artist_back: "Retour au catalogue",
    detail_album_label: "Album",
    detail_album_artist: "Artiste :",
    detail_album_release: "Sortie :",
    detail_album_total: "Total chansons :",
    detail_album_list_title: "Liste des Chansons",
    detail_album_listen: "Écouter",
    detail_album_title_col: "Titre",
    detail_album_genres: "Genres",
    detail_album_duration: "Durée",
    detail_album_reps: "Écoutes",
    detail_album_no_genre: "Sans genre",
    detail_album_empty: "Cet album ne contient aucune chanson enregistrée.",
    detail_album_back: "Retour au catalogue",
    detail_album_see_artist: "Voir l'artiste",
    detail_playlist_public: "Publique",
    detail_playlist_private: "Privée",
    detail_playlist_creator: "Créateur :",
    detail_playlist_total: "Total chansons :",
    detail_playlist_list_title: "Chansons de la Playlist",
    detail_playlist_order: "Ordre",
    detail_playlist_listen: "Écouter",
    detail_playlist_title_col: "Titre",
    detail_playlist_artist: "Artiste",
    detail_playlist_album: "Album",
    detail_playlist_duration: "Durée",
    detail_playlist_empty: "Cette playlist est vide.",
    detail_playlist_back: "Retour à l'accueil"
  },
  it: {
    nav_inicio: "Inizio",
    nav_catalogo: "Catalogo",
    nav_historial: "Cronologia",
    nav_suscripcion: "Abbonamento",
    nav_reportes: "Report",
    nav_soporte: "Supporto",
    nav_planes: "Piani",
    nav_administracion: "Amministrazione",
    sidebar_user_plan_label: "Piano: ",
    sidebar_btn_cerrar_sesion: "Disconnettersi",
    dropdown_ajustes: "Impostazioni",
    dropdown_idioma: "Lingua",
    dropdown_ayuda: "Chiedi aiuto",
    dropdown_planes: "Piani",
    dropdown_suscripcion: "Abbonamento",
    dropdown_info: "Maggiori informazioni",
    dropdown_cerrar_sesion: "Esci",
    public_nav_soporte: "Supporto",
    public_nav_planes: "Piani",
    public_nav_iniciar_sesion: "Accedi",
    public_nav_registrarse: "Registrati",
    footer_copyright: "SoundWave. Tutti i diritti riservati.",
    lang_modal_title: "Seleziona Lingua",
    lang_modal_close: "Chiudi",
    admin_modal_title: "Verifica di accesso",
    admin_modal_placeholder: "Password Amministratore",
    admin_modal_confirm: "Conferma",
    admin_modal_cancel: "Annulla",
    admin_sidebar_mode: "Modalità Amministratore",
    admin_sidebar_oyentes: "Ascoltatori",
    admin_sidebar_artistas: "Artisti",
    admin_sidebar_sistema: "Sistema",
    admin_sidebar_reportes: "Report",
    admin_sidebar_user_profile: "Admin Attivo",
    admin_header_title: "Console di controllo del sistema",
    admin_title: "Pannello di Amministrazione",
    admin_subtitle: "Console di controllo",
    admin_oyentes_title: "Ascoltatori Registrati",
    admin_oyentes_subtitle: "Gestione Utenti",
    admin_oyentes_search_label: "Cerca Ascoltatore",
    admin_oyentes_filter_status: "Stato",
    admin_oyentes_filter_all: "Tutti",
    admin_oyentes_filter_active: "Attivo",
    admin_oyentes_filter_inactive: "Inattivo",
    admin_oyentes_filter_plan: "Piano",
    admin_oyentes_filter_any: "Qualsiasi",
    admin_oyentes_table_id: "ID",
    admin_oyentes_table_name: "Nome",
    admin_oyentes_table_email: "Indirizzo e-mail",
    admin_oyentes_table_plan: "Piano",
    admin_oyentes_table_status: "Stato",
    admin_oyentes_table_actions: "Azioni",
    admin_oyentes_btn_edit: "Modifica",
    admin_oyentes_btn_delete: "Elimina",
    admin_oyentes_btn_protected: "Protetto",
    admin_oyentes_create_title: "Registra Nuovo Ascoltatore",
    admin_oyentes_create_sub: "Nuova Registrazione",
    admin_oyentes_create_name: "Nome Completo",
    admin_oyentes_create_email: "Indirizzo e-mail",
    admin_oyentes_create_country: "Paese",
    admin_oyentes_create_plan: "Piano Iniziale",
    admin_oyentes_create_btn: "Registra Ascoltatore",
    admin_oyentes_edit_title: "Modifica Profilo Ascoltatore",
    admin_oyentes_edit_sub: "Aggiorna Dati",
    admin_oyentes_edit_name: "Nome",
    admin_oyentes_edit_email: "E-mail",
    admin_oyentes_edit_status: "Stato",
    admin_oyentes_edit_btn_cancel: "Annulla",
    admin_oyentes_edit_btn_save: "Salva",
    admin_artistas_title: "Artisti sulla Piattaforma",
    admin_artistas_sub: "Catalogo Artisti",
    admin_artistas_search_label: "Cerca Artista",
    admin_artistas_table_name: "Artista",
    admin_artistas_table_country: "Paese",
    admin_artistas_table_plays: "Riproduzioni Totali",
    admin_sistema_users: "Utenti Totali",
    admin_sistema_songs: "Canzoni in Catalogo",
    admin_sistema_albums: "Album Registrati",
    admin_sistema_plays: "Riproduzioni Totali",
    landing_hero_title: "L'ondata di suono <span class=\"accent\">definitiva</span>",
    landing_hero_subtitle: "Qualità acustica senza compromessi. Ascolta milioni di canzoni in alta fedeltà e connettiti profondamente con la visione degli artisti.",
    landing_btn_probar: "Prova Gratis",
    landing_btn_ver_planes: "Vedi i Piani",
    landing_features_title: "Suono Premium, Esperienza Esclusiva",
    landing_features_subtitle: "Progettato per gli audiofili che apprezzano la purezza e i dettagli in ogni nota musicale.",
    landing_feat1_title: "Alta Fedeltà (Hi-Res)",
    landing_feat1_desc: "Streaming audio a 24 bit senza perdite per percepire ogni strumento proprio come è stato registrato.",
    landing_feat2_title: "Catalogo Curato",
    landing_feat2_desc: "Selezione esclusiva di artisti, album e playlist progettati per arricchire i tuoi sensi.",
    landing_feat3_title: "Senza Pubblicità",
    landing_feat3_desc: "Concentrazione totale sulla musica senza interruzioni o fastidiosi annunci commerciali.",
    landing_feat4_title: "Algoritmo Personalizzato",
    landing_feat4_desc: "Raccomandazioni basate sui tuoi gusti reali e sui modelli di ascolto acustico.",
    landing_drive_title: "Inizia il tuo viaggio musicale oggi",
    landing_drive_subtitle: "Accedi subito all'intero catalogo e sperimenta la differenza.",
    landing_drive_btn: "Registrati Ora",
    planes_title: "Trova il tuo piano ideale",
    planes_subtitle: "Cambia piano in qualsiasi momento in base alle tue esigenze acustiche e goditi SoundWave.",
    planes_tab_gratuito_title: "Piano Gratuito",
    planes_tab_gratuito_price: "$0 / sempre",
    planes_tab_gratuito_feat1: "Accesso al catalogo completo delle canzoni",
    planes_tab_gratuito_feat2: "Riproduzione con qualità standard (128kbps)",
    planes_tab_gratuito_feat3: "Supporto tecnico tramite centro assistenza",
    planes_tab_gratuito_feat4: "Annunci visivi e audio occasionali",
    planes_tab_gratuito_btn: "Inizia Gratis",
    planes_tab_premium_title: "Piano Premium",
    planes_tab_premium_price: "$9.99 / mese",
    planes_tab_premium_feat1: "Audio ad alta risoluzione senza perdite (Hi-Res a 24 bit)",
    planes_tab_premium_feat2: "Riproduzione al 100% senza pubblicità e senza interruzioni",
    planes_tab_premium_feat3: "Esportazione della cronologia di riproduzione in formato PDF",
    planes_tab_premium_feat4: "Supporto tecnico prioritario e specializzato",
    planes_tab_premium_btn: "Acquista Premium",
    planes_active_plan_btn: "Il tuo piano attuale",
    planes_tab_premium_upgrade_btn: "Passa a Premium",
    planes_faq_title: "Domande frequenti sui piani",
    planes_faq_q1: "Posso cancellare il mio piano in qualsiasi momento?",
    planes_faq_a1: "Sì, puoi cancellare il tuo abbonamento Premium in qualsiasi momento dal tuo pannello di abbonamento. Continuerai ad avere accesso ai vantaggi fino alla fine del periodo di fatturazione.",
    planes_faq_q2: "Come vengono elaborati i pagamenti?",
    planes_faq_a2: "I pagamenti vengono elaborati in modo sicuro attraverso il nostro gateway di pagamento certificato, con crittografia end-to-end. L'abbonamento si attiva immediatamente dopo la conferma della transazione.",
    planes_faq_more: "Hai altre domande? Visita il nostro Centro Assistenza",
    planes_cta_title: "Inizia con SoundWave oggi stesso",
    planes_cta_text: "Unisciti a milioni di ascoltatori e goditi una qualità del suono insuperabile adatta al tuo stile di vita",
    planes_cta_btn_dashboard: "Vai alla mia Dashboard",
    planes_cta_btn_start: "Inizia ora",
    soporte_title: "Centro Assistenza",
    soporte_subtitle: "Trova risposte rapide sul tuo account, sui piani e sulla riproduzione",
    soporte_cat1_title: "Account e Sicurezza",
    soporte_cat1_desc: "Modificare l'e-mail, recuperare la password e gestire le sessioni",
    soporte_cat2_title: "Piani e Pagamenti",
    soporte_cat2_desc: "Metodi di pagamento, fatturazione e passaggio a Premium",
    soporte_cat3_title: "Riproduzione e Qualità",
    soporte_cat3_desc: "Impostazioni audio Hi-Res, codec e risoluzione dei problemi",
    soporte_faq_title: "Domande Frequenti",
    soporte_q1: "Come posso cambiare il mio piano da Gratuito a Premium?",
    soporte_a1: "Puoi cambiare il tuo piano in qualsiasi momento dalla sezione Abbonamento nel menu del pannello laterale. Seleziona il piano Premium, inserisci il metodo di pagamento e il tuo account verrà aggiornato immediatamente.",
    soporte_q2: "Cos'è l'audio ad alta risoluzione (Hi-Res)?",
    soporte_a2: "L'audio Hi-Res di SoundWave offre un suono a 24 bit senza perdite, preservando tutti i dettagli e la gamma dinamica della registrazione originale in studio. Richiede un abbonamento Premium attivo.",
    soporte_q3: "Come recupero la mia password di accesso?",
    soporte_a3: "Se non ricordi la password, puoi andare alla schermata di accesso e cliccare su \"Password dimenticata?\", o contattare l'assistenza se riscontri ulteriori problemi.",
    soporte_search_placeholder: "Cerca la tua domanda...",
    soporte_no_results: "Non abbiamo trovato domande corrispondenti alla tua ricerca. Prova altre parole chiave.",
    soporte_contact_title: "Non hai trovato quello che cercavi?",
    soporte_contact_text: "Il nostro team di assistenza clienti è sempre pronto ad aiutarti con un supporto tecnico e amministrativo personalizzato.",
    soporte_contact_btn: "Contattaci via Email",
    dashboard_welcome: "Benvenuto",
    dashboard_sub: "Esplora la tua musica e le tue statistiche in tempo reale",
    dashboard_stat_songs: "Canzoni Ascoltate",
    dashboard_stat_albums: "Album Salvati",
    dashboard_stat_hours: "Ore di Ascolto",
    dashboard_title_recientes: "Cronologia Recente",
    dashboard_col_song: "Canzone",
    dashboard_col_artist: "Artista",
    dashboard_col_date: "Data e Ora",
    dashboard_title_top: "Top Canzoni Globali",
    dashboard_col_reps: "Riproduzioni",
    dashboard_col_duration: "Durata",
    dashboard_title_recs: "Raccomandazioni per te",
    dashboard_col_genre: "Genere",
    dashboard_empty_albums: "Non hai album salvati nella tua libreria.",
    dashboard_empty_history: "Nessuna riproduzione registrata di recente.",
    dashboard_empty_recs: "Nessuna raccomandazione trovata in base alla tua cronologia.",
    dashboard_stat_songs_sub: "Attività reale sulla piattaforma",
    dashboard_stat_albums_sub: "Sincronizzati nella tua libreria",
    dashboard_stat_hours_sub: "Tempo totale su SoundWave",
    dashboard_profile_title: "Profilo Editoriale",
    dashboard_profile_name: "Nome dell'Ascoltatore",
    dashboard_profile_subscription: "Livello di Abbonamento",
    dashboard_profile_status: "Stato dell'Account",
    dashboard_profile_premium_active: "Premium Attivo",
    dashboard_profile_free_account: "Account Gratuito",
    dashboard_library_title: "Libreria Personale",
    dashboard_library_sub: "Collezione di Album",
    dashboard_col_reg_date: "Data di Registrazione",
    dashboard_empty_library: "La tua libreria personale è vuota.",
    dashboard_recs_sub: "Scoperte per te",
    dashboard_recent_sub: "Ultime Riproduzioni",
    dashboard_top_sub: "Le più ascoltate",
    dashboard_empty_top: "Nessun dato di riproduzione accumulato registrato.",
    catalogo_title: "Catalogo Canzoni",
    catalogo_subtitle: "Esplora canzoni, album e playlist popolari su SoundWave",
    catalogo_filter_artist: "Artista",
    catalogo_filter_all_artists: "Tutti gli artisti",
    catalogo_filter_genre: "Genere",
    catalogo_filter_all_genres: "Tutti i generi",
    catalogo_btn_apply: "Applica Filtri",
    catalogo_btn_clear: "Rimuovi Filtri",
    catalogo_title_songs: "Risultati della Ricerca",
    catalogo_col_album: "Album",
    catalogo_btn_play: "Ascolta",
    catalogo_title_popular_artists: "Artisti Popolari",
    catalogo_col_country: "Paese",
    catalogo_col_total_plays: "Riproduzioni",
    catalogo_search_label: "Cerca canzone o artista",
    catalogo_search_placeholder: "Titolo, artista o album...",
    catalogo_ranking_sub: "Classifica per riproduzioni",
    catalogo_col_rank: "Posizione",
    catalogo_col_country: "Paese d'Origine",
    catalogo_col_plays: "Riproduzioni Totali",
    catalogo_empty_artists_search: "Nessun artista corrisponde alla ricerca.",
    catalogo_empty_artists: "Nessun artista registrato nel catalogo.",
    catalogo_top_20_plays: "Top 20 Più Ascoltate",
    catalogo_col_play: "Ascolta",
    catalogo_col_title: "Titolo",
    catalogo_col_duration: "Durata",
    catalogo_empty_songs_search: "Nessuna canzone corrisponde alla ricerca.",
    catalogo_empty_songs: "Nessuna canzone registrata con i filtri selezionati.",
    catalogo_filtering_by: "Filtrato per:",
    catalogo_remove_filter: "Rimuovi filtro",
    historial_title: "Cronologia di Riproduzione",
    historial_subtitle: "Visualizza e filtra tutte le tue riproduzioni sulla piattaforma",
    historial_filter_start: "Data Inizio",
    historial_filter_end: "Data Fine",
    historial_btn_filter: "Filtra Cronologia",
    historial_btn_pdf: "Esporta PDF",
    historial_col_duration: "Tempo di Ascolto",
    historial_empty: "Nessuna riproduzione trovata per i filtri selezionati.",
    historial_filter_genre: "Filtra per Genere",
    historial_filter_all_genres: "Tutti i generi",
    historial_audit_report: "Report di Audit",
    historial_top_10_title: "Top 10 dell'Ascoltatore",
    historial_recent_badge: "Recenti",
    historial_empty_top: "Nessuna riproduzione disponibile.",
    suscripcion_title: "Gestione Abbonamento",
    suscripcion_active_plan: "Piano Attualmente Attivo",
    suscripcion_active_plan_val: "Piano Attivo",
    suscripcion_start_date: "Data Inizio",
    suscripcion_end_date: "Prossimo Rinnovo",
    suscripcion_status: "Stato dell'abbonamento",
    suscripcion_active_val: "Attiva",
    suscripcion_change_title: "Vuoi cambiare piano?",
    suscripcion_change_desc: "Se desideri aggiornare l'abbonamento o annullare il rinnovo, puoi farlo selezionando un nuovo piano nella sezione piani.",
    suscripcion_btn_planes: "Vedi i Piani Disponibili",
    suscripcion_btn_cancel: "Cancella Account",
    sub_res_title: "Risultato della transazione in SoundWaveDB",
    sub_res_plan: "Piano dell'Account:",
    sub_res_date: "Nuova Data di Scadenza:",
    sub_res_db_status: "Stato aggiornato nel DB:",
    sub_status_title: "Stato dell'abbonamento attuale (Query DB)",
    sub_payment_gateway_title: "Gateway di Pagamento Interno",
    sub_payment_gateway_desc: "Stai gestendo il ciclo di vita transazionale per l'abbonamento dell'account <strong>ID Abbonamento: 1</strong>. L'operazione invocherà in modo atomico le regole di business nel server SQL Server.",
    sub_label_payment_method: "Metodo di Pagamento Aziendale",
    sub_opt_credit_card: "Carta di Credito Aziendale",
    sub_opt_paypal: "PayPal Business",
    sub_opt_bank_transfer: "Bonifico Bancario Diretto",
    sub_label_simulate_status: "Simula lo Stato della Transazione",
    sub_opt_success: "Transazione Riuscita (Approva Rinnovo)",
    sub_opt_fail: "Transazione Rifiutata (Forza Scadenza)",
    sub_btn_process: "Elabora Transazione nel Database",
    sub_val_indefinite: "Indefinita",
    sub_val_inactive: "Inattiva",
    reportes_title: "Report e Statistiche",
    reportes_subtitle: "Report di riproduzione globali e attività del sistema",
    reportes_tab_plays: "Riproduzioni",
    reportes_tab_users: "Utenti",
    reportes_tab_artistas: "Artisti",
    reportes_tab_planes: "Abbonamenti",
    reportes_plays_title: "Report Canzoni Popolari",
    reportes_plays_col_song: "Canzone",
    reportes_plays_col_artist: "Artista",
    reportes_plays_col_duration: "Durata",
    reportes_plays_col_reps: "Riproduzioni",
    reportes_users_title: "Report Ascoltatori Registrati",
    reportes_users_col_name: "Nome",
    reportes_users_col_email: "Indirizzo e-mail",
    reportes_users_col_status: "Stato",
    reportes_users_col_plan: "Piano",
    reportes_artistas_title: "Report Artisti",
    reportes_artistas_col_name: "Artista",
    reportes_artistas_col_country: "Paese",
    reportes_artistas_col_reps: "Riproduzioni Totali",
    reportes_planes_title: "Distribuzione Piani di Abbonamento",
    reportes_planes_col_plan: "Tipo di Piano",
    reportes_planes_col_count: "Numero Utenti",
    detail_artist_title: "Profilo Artista",
    detail_artist_country: "Paese d'Origine",
    detail_artist_plays: "Riproduzioni Totali",
    detail_artist_songs: "Canzoni Popolari",
    detail_album_title: "Dettagli Album",
    detail_album_release: "Anno di Rilascio",
    detail_album_songs: "Canzoni dell'Album",
    detail_playlist_title: "Dettagli Playlist",
    detail_playlist_owner: "Creato da",
    detail_playlist_songs: "Canzoni nella Playlist",
    ajustes_title: "Impostazioni Profilo",
    ajustes_subtitle: "Il mio Account",
    ajustes_label_name: "Nome Utente",
    ajustes_label_email: "Indirizzo e-mail",
    ajustes_label_pass: "Password",
    ajustes_btn_save: "Salva Modifiche",
    info_about_title: "Informazioni su SoundWave",
    info_about_sub: "La nostra Missione",
    info_about_desc: "SoundWave è una piattaforma di streaming musicale premium progettata per connettere gli ascoltatori con i loro artisti preferiti. Fondata sull'eleganza della semplicità e su un design di alta qualità, ci dedichiamo a offrire un'esperienza sonora senza compromessi, dove la fedeltà audio e il rispetto per la creatività artistica convergono.",
    info_team_title: "Team di Sviluppo",
    info_team_sub: "Creatori",
    info_team_role_backend: "Sviluppatore Backend",
    info_team_role_frontend: "Sviluppatrice Frontend",
    info_team_role_fullstack: "Sviluppatore Fullstack",
    info_terms_title: "Termini e Condizioni",
    info_terms_sub: "Note Legali",
    info_terms_desc1: "Accedendo e utilizzando SoundWave, accetti di essere vincolato dai seguenti termini e condizioni di servizio. La piattaforma fornisce l'accesso a contenuti audio in streaming con abbonamenti gratuiti e premium.",
    info_terms_desc2: "Tutti i contenuti musicali, le copertine degli album, i metadati e il codice software sono proprietà intellettuale esclusiva di SoundWave e dei suoi licenzianti. L'uso della piattaforma è strettamente personale e non commerciale.",
    info_terms_desc3: "Ci riserviamo il diritto di modificare o ritirare qualsiasi parte del servizio, incluse tariffe, piani e disponibilità del catalogo in qualsiasi momento e senza preavviso.",
    reportes_page_title: "Report Esecutivi e di Audit",
    reportes_page_sub: "Database SoundWave",
    reportes_page_desc: "Esecuzione diretta di Stored Procedure ed esportazione PDF con design istituzionale. Seleziona uno dei report per configurare i parametri e visualizzare o scaricare i risultati.",
    rep1_title: "Top 10 Canzoni Più Ascoltate",
    rep1_desc: "Mostra le 10 canzoni con il maggior numero di riproduzioni sulla piattaforma, con artista, album e totale riproduzioni.",
    rep2_title: "Artisti Più Popolari",
    rep2_desc: "Classifica degli artisti della piattaforma ordinati per il totale di riproduzioni accumulate di tutte le canzoni pubblicate.",
    rep3_title: "Abbonamenti Attivi",
    rep3_desc: "Mostra tutti gli utenti con abbonamenti in stato attivo o premium, incluse le date di inizio, fine e importi pagati.",
    rep4_title: "Entrate e Royalty per Artista",
    rep4_select_artist: "Seleziona Artista",
    rep4_select_option: "-- Seleziona un Artista --",
    rep5_title: "Cronologia di Riproduzione per Utente",
    rep5_select_user: "Seleziona Ascoltatore",
    rep5_select_option: "-- Seleziona un Utente --",
    rep5_date_from: "Da (Opzionale)",
    rep5_date_to: "A (Opzionale)",
    rep6_title: "Album Salvati per Utente",
    rep6_select_user: "Seleziona Ascoltatore",
    rep6_select_option: "-- Seleziona un Utente --",
    rep_btn_view: "Vedi Report",
    rep_btn_pdf: "Scarica PDF",
    rep_results_title: "Risultati della Query",
    rep_results_error: "Errore nell'esecuzione della stored procedure:",
    rep_results_empty: "Nessun record trovato per i parametri selezionati.",
    detail_artist_label: "Artista",
    detail_artist_debut: "Debutto:",
    detail_artist_contact: "Contatto:",
    detail_artist_total_plays: "Totale Riproduzioni:",
    detail_artist_albums: "Album e Singoli",
    detail_artist_listen: "Ascolta",
    detail_artist_title_col: "Titolo",
    detail_artist_duration: "Durata",
    detail_artist_reps: "Riproduzioni",
    detail_artist_empty_album: "Questo album non contiene canzoni registrate.",
    detail_artist_no_albums: "Nessun album registrato per questo artista.",
    detail_artist_back: "Torna al catalogo",
    detail_album_label: "Album",
    detail_album_artist: "Artista:",
    detail_album_release: "Uscita:",
    detail_album_total: "Totale Canzoni:",
    detail_album_list_title: "Lista Canzoni",
    detail_album_listen: "Ascolta",
    detail_album_title_col: "Titolo",
    detail_album_genres: "Generi",
    detail_album_duration: "Durata",
    detail_album_reps: "Riproduzioni",
    detail_album_no_genre: "Senza genere",
    detail_album_empty: "Questo album non contiene canzoni registrate.",
    detail_album_back: "Torna al catalogo",
    detail_album_see_artist: "Vedi Artista",
    detail_playlist_public: "Pubblica",
    detail_playlist_private: "Privata",
    detail_playlist_creator: "Creatore:",
    detail_playlist_total: "Totale Canzoni:",
    detail_playlist_list_title: "Canzoni nella Playlist",
    detail_playlist_order: "Ordine",
    detail_playlist_listen: "Ascolta",
    detail_playlist_title_col: "Titolo",
    detail_playlist_artist: "Artista",
    detail_playlist_album: "Album",
    detail_playlist_duration: "Durata",
    detail_playlist_empty: "Questa playlist è vuota.",
    detail_playlist_back: "Torna alla Home"
  }
};
